export const RECEIVE_UNFINISHED_GAME = 'game/RECEIVE_UNFINISHED_GAME';
export const UPDATE_SCORE_TEAM1 = 'game/UPDATE_SCORE_TEAM1';
export const UPDATE_SCORE_TEAM2 = 'game/UPDATE_SCORE_TEAM2';
export const FINISH_GAME = 'game/FINISH_GAME';
export const RESET_GAME = 'game/RESET_GAME';
export const SET_GOAL_LIMIT = 'game/SET_GOAL_LIMIT';
export const SELECT_PLAYER1 = 'game/SELECT_PLAYER1';
export const SELECT_PLAYER2 = 'game/SELECT_PLAYER2';
export const SELECT_PLAYER3 = 'game/SELECT_PLAYER3';
export const SELECT_PLAYER4 = 'game/SELECT_PLAYER4';
export const REMOVE_PLAYER2 = 'game/REMOVE_PLAYER2';
export const REMOVE_PLAYER3 = 'game/REMOVE_PLAYER3';
export const REMOVE_PLAYER4 = 'game/REMOVE_PLAYER4';
export const DEFAULT_GOAL_NUMBER = '7';
export const DEFAULT_GOAL_LIMIT = '11';
export const SET_GAME_TO_DEFAULT = 'game/SET_GAME_TO_DEFAULT';
export const FETCH_PLAYERS_FOR_SELECTION = 'game/FETCH_PLAYERS_FOR_SELECTION';
export const PLAYERS_RECEIVED = 'game/PLAYERS_RECEIVED';
export const RECEIVING_PLAYERS = 'game/RECEIVING_PLAYERS';
export const RESET_PLAYERS = 'game/RESET_PLAYERS';


