export const FETCH_RECENT_GAMES = 'recentGames/FETCH_RECENT_GAMES';
export const RECEIVING_RECENT_GAMES = 'recentGames/RECEIVING_RECENT_GAMES';
export const RECENT_GAMES_RECEIVED = 'recentGames/RECENT_GAMES_RECEIVED';
